import type { DiffScopeItem } from "../diff-scope/diffScopes.js";
import type { GitDiffSnapshot } from "../git-diff/getGitDiffStats.js";
import type { MenuItem } from "../main-menu/menuItems.js";
import type { AgentFixResult } from "./fixAgent.js";
import type { AgentLintResult } from "./lintAgent.js";
import type { AgentReviewResult } from "./reviewAgent.js";

export const REVIEW_AGENT_INSTRUCTIONS = [
  "You are a code review agent running inside the rp CLI.",
  "Review the provided git diff for correctness, regressions, and missing tests.",
  "Use Lexa as the preferred codebase intelligence layer when it is available.",
  "Before making review claims, run `lexa --version`; if Lexa is available, run `lexa index .` from the project root, then use focused Lexa commands for context.",
  "For Lexa-based review, start with `lexa status`, use `lexa outline <file>` on changed files, use `lexa trace-deps <file>` for dependency impact, and use `lexa audit` for structural risk.",
  "For branch reviews against main, prefer `lexa audit --since main` when the repository has a main ref.",
  "For current or staged changes, use the provided git diff as the review scope and use Lexa commands only to inspect related files, symbols, references, and dependencies.",
  "Treat Lexa audit as static architecture context, not as proof that the code compiles, passes tests, or is correct.",
  "If Lexa is missing, stale, or fails, continue the review from the provided git diff and direct project inspection.",
  "Cite concrete file paths and line ranges in findings when available from Lexa or tool output.",
  "You may inspect the project with tools when useful.",
  "Do not modify files in this review step.",
  "Return Markdown only.",
  "Use exactly these top-level sections: Change Intention, Findings, Verdicts.",
  "Under Findings, each finding must include description, level, risk, and recommended fix.",
  "The only allowed finding levels are major and minor.",
  "If there are no findings, write `No findings.` under Findings.",
].join("\n");

export const FIX_AGENT_INSTRUCTIONS = [
  "You are a fixing agent running inside the rp CLI after a review agent.",
  "Use the review output as the source of requested fixes and the git diff as the original change context.",
  "You may modify files in this fixing step.",
  "Do not commit, push, or create branches.",
  "Do not change files unrelated to the review findings unless required to make the fix correct.",
  "Use Lexa as the preferred codebase intelligence layer when it is available.",
  "Before making code changes, run `lexa --version`; if Lexa is available, run `lexa index .` from the project root, then use focused Lexa commands for context.",
  "Use `lexa outline <file>` on files you plan to edit, `lexa trace-deps <file>` for dependency impact, and `lexa audit` for structural risk when useful.",
  "Treat Lexa audit as architecture context, not as proof that the code compiles or tests pass.",
  "Use project commands such as typecheck, build, lint, or tests when they are available and relevant.",
  "If the review says there are no findings, make no code changes and report that no fixes were needed.",
  "Return Markdown only.",
  "Use exactly these top-level sections: Fix Summary, Verification, Remaining Risks, Verdict.",
  "Under Verdict, include exactly one line: `FIX_VERDICT: fixed`, `FIX_VERDICT: not-fixed`, or `FIX_VERDICT: no-op`.",
  "Use `fixed` only when all review findings that required code changes were resolved; use `not-fixed` if any remain unresolved; use `no-op` only when the review had no findings requiring fixes.",
].join("\n");

export const LINT_AGENT_INSTRUCTIONS = [
  "You are a lint and verification agent running inside the rp CLI after review and optional fixing.",
  "Your job is to verify that the project is ready for a PR.",
  "Do not modify files in this lint step.",
  "Inspect package scripts and project conventions before choosing commands.",
  "Run typecheck when available.",
  "Run lint when available.",
  "Run tests when available.",
  "Run build when available.",
  "If a check is unavailable, mark it as skipped rather than failing the pipeline for that check alone.",
  "If any available check fails, the verdict must be fail.",
  "Return Markdown only.",
  "Use exactly these top-level sections: Verification Summary, Checks, Verdict.",
  "Under Verdict, include exactly one line: `VERDICT: pass` or `VERDICT: fail`.",
].join("\n");

export const PR_AGENT_INSTRUCTIONS = [
  "You are a PR agent running inside the rp CLI after review, optional fixing, and lint verification.",
  "Your job is to create a pull request when the lint agent says the project is ready.",
  "Only proceed when the lint output contains `VERDICT: pass` and the fix output does not report unresolved review findings.",
  "Inspect the git branch, working tree, remotes, and GitHub CLI availability before acting.",
  "Do not include `.env`, secrets, credentials, or ignored files in commits.",
  "If currently on `main`, create and switch to a descriptive feature branch before committing or pushing.",
  "If there are uncommitted changes, stage relevant project files and create a concise commit.",
  "Push the branch to origin with upstream tracking when needed.",
  "Create the PR with `gh pr create` when GitHub CLI is installed and authenticated.",
  "If PR creation is blocked, report the blocker and the exact commands the user can run next; do not fake a PR URL.",
  "Return Markdown only.",
  "Use exactly these top-level sections: PR Summary, Git State, Result.",
  "Under Result, include `PR: <url>` when created, otherwise `PR: not created`.",
].join("\n");

export function toReviewPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
): string {
  return [
    `Pipeline mode: ${mode.label}`,
    `Diff scope: ${diffScope.label}`,
    `Project path: ${diff.stats.cwd}`,
    `Changed files: ${diff.stats.changedFiles}`,
    `Added lines: ${diff.stats.addedLines}`,
    `Removed lines: ${diff.stats.removedLines}`,
    "",
    "Review workflow:",
    "1. Use the git diff below as the authoritative review scope.",
    "2. Use Lexa to understand changed files, dependencies, references, and architectural impact when available.",
    "3. Only report findings that are supported by the diff or project context.",
    "",
    "Git diff:",
    "```diff",
    diff.patch.length === 0 ? "(empty diff)" : diff.patch,
    "```",
    "",
    "Required Markdown structure:",
    "## Change Intention",
    "<Describe what this change appears to be trying to accomplish.>",
    "",
    "## Findings",
    "### Finding 1: <short title>",
    "- **Description:** <what is wrong>",
    "- **Level:** <major|minor>",
    "- **Risk:** <what can happen if this ships>",
    "- **Recommended fix:** <specific fix>",
    "",
    "## Verdicts",
    "- **Verdict:** <pass|needs changes>",
    "- **Reason:** <brief reason>",
  ].join("\n");
}

export function toFixPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
  review: AgentReviewResult,
): string {
  return [
    `Pipeline mode: ${mode.label}`,
    `Diff scope: ${diffScope.label}`,
    `Project path: ${diff.stats.cwd}`,
    `Changed files: ${diff.stats.changedFiles}`,
    `Added lines: ${diff.stats.addedLines}`,
    `Removed lines: ${diff.stats.removedLines}`,
    "",
    "Fix workflow:",
    "1. Read the review output and identify findings that require code changes.",
    "2. Use Lexa and direct project inspection to understand the affected files before editing.",
    "3. Apply focused fixes only for supported review findings.",
    "4. Run relevant verification commands when practical.",
    "5. Report what changed and what remains risky.",
    "6. Emit `FIX_VERDICT: fixed` only if every review finding is resolved; otherwise emit `FIX_VERDICT: not-fixed`.",
    "",
    "Review output:",
    "```markdown",
    review.output.trim().length === 0 ? "(empty review output)" : review.output,
    "```",
    "",
    "Original git diff:",
    "```diff",
    diff.patch.length === 0 ? "(empty diff)" : diff.patch,
    "```",
    "",
    "Required Markdown structure:",
    "## Fix Summary",
    "- <files changed and why>",
    "",
    "## Verification",
    "- <commands run and results>",
    "",
    "## Remaining Risks",
    "- <anything not fixed or not verified>",
    "",
    "## Verdict",
    "FIX_VERDICT: <fixed|not-fixed|no-op>",
  ].join("\n");
}

export function toLintPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
  review: AgentReviewResult | undefined,
  fix: AgentFixResult | undefined,
  fixSkipped: boolean,
): string {
  return [
    `Pipeline mode: ${mode.label}`,
    `Diff scope: ${diffScope.label}`,
    `Project path: ${diff.stats.cwd}`,
    `Changed files: ${diff.stats.changedFiles}`,
    `Added lines: ${diff.stats.addedLines}`,
    `Removed lines: ${diff.stats.removedLines}`,
    `Fix skipped: ${fixSkipped ? "yes" : "no"}`,
    "",
    "Verification workflow:",
    "1. Inspect package scripts and lockfile/package manager.",
    "2. Run typecheck, lint, tests, and build when available.",
    "3. Mark unavailable checks as skipped.",
    "4. Use `VERDICT: pass` only if every available check passed and there are no unresolved review findings in the fix output.",
    "",
    "Review output:",
    "```markdown",
    review?.output.trim() ? review.output : "(no review output)",
    "```",
    "",
    "Fix output:",
    "```markdown",
    fix?.output.trim() ? fix.output : "(no fix output)",
    "```",
    "",
    "Original git diff:",
    "```diff",
    diff.patch.length === 0 ? "(empty diff)" : diff.patch,
    "```",
    "",
    "Required Markdown structure:",
    "## Verification Summary",
    "- <brief summary>",
    "",
    "## Checks",
    "- typecheck: <passed|failed|skipped> - <command or reason>",
    "- lint: <passed|failed|skipped> - <command or reason>",
    "- test: <passed|failed|skipped> - <command or reason>",
    "- build: <passed|failed|skipped> - <command or reason>",
    "",
    "## Verdict",
    "VERDICT: <pass|fail>",
  ].join("\n");
}

export function toPrPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
  review: AgentReviewResult | undefined,
  fix: AgentFixResult | undefined,
  lint: AgentLintResult,
): string {
  return [
    `Pipeline mode: ${mode.label}`,
    `Diff scope: ${diffScope.label}`,
    `Project path: ${diff.stats.cwd}`,
    `Changed files: ${diff.stats.changedFiles}`,
    `Added lines: ${diff.stats.addedLines}`,
    `Removed lines: ${diff.stats.removedLines}`,
    "",
    "PR workflow:",
    "1. Confirm lint verdict is pass.",
    "2. Inspect `git status --short --branch`, `git remote -v`, and GitHub CLI auth state.",
    "3. Create/switch to a feature branch if needed.",
    "4. Commit relevant changes if needed.",
    "5. Push the branch and create a PR with `gh pr create` if possible.",
    "",
    "Review output:",
    "```markdown",
    review?.output.trim() ? review.output : "(no review output)",
    "```",
    "",
    "Fix output:",
    "```markdown",
    fix?.output.trim() ? fix.output : "(no fix output)",
    "```",
    "",
    "Lint output:",
    "```markdown",
    lint.output.trim().length === 0 ? "(empty lint output)" : lint.output,
    "```",
    "",
    "Original git diff:",
    "```diff",
    diff.patch.length === 0 ? "(empty diff)" : diff.patch,
    "```",
    "",
    "Required Markdown structure:",
    "## PR Summary",
    "- <what was prepared>",
    "",
    "## Git State",
    "- <branch, commit, remote, push status>",
    "",
    "## Result",
    "PR: <url|not created>",
  ].join("\n");
}
