import type { DiffScopeItem } from "../diff-scope/index.js";
import type { GitDiffSnapshot } from "../git-diff/index.js";
import type { MenuItem } from "../main-menu/index.js";
import type {
  AgentPrMonitorResult,
  AgentPrResult,
  VerificationRunPhase,
  PromptAgentOutput,
} from "./types.js";
import { extractChangedFilePaths } from "./utils.js";

export const FIX_AGENT_INSTRUCTIONS = [
  "You are a fixing agent running inside the review-this CLI after a review agent.",
  "Use the review output and verification output as the sources of requested fixes, with the git diff as the original change context.",
  "Prefer editing files already changed in the diff, but you may edit additional project files when review findings or verification failures prove they are required.",
  "Any out-of-diff edit must be directly tied to a reported review finding or failed check, and you must name the reason in Fix Summary.",
  "Do not edit secrets, `.env` files, credentials, ignored files, generated files without the project's generator, or unrelated files.",
  "Do not stage, commit, push, or create branches.",
  "Do not change files unrelated to the review findings or verification failures, even when they are in the original diff.",
  "If the verification output reports failing checks, fix supported failures with the smallest relevant project change.",
  "Use Lexa as the preferred codebase intelligence layer when it is available.",
  "Before making code changes, run `lexa --version`; if Lexa is available, run `lexa index .` from the project root, then use focused Lexa commands for context.",
  "Use `lexa outline <file>` on files you plan to edit, `lexa trace-deps <file>` for dependency impact, and `lexa audit` for structural risk when useful.",
  "Treat Lexa audit as architecture context, not as proof that the code compiles or tests pass.",
  "Use project commands such as typecheck, build, lint, or tests when they are available and relevant.",
  "If the review says there are no findings and the verification output has no failed checks, make no code changes and report that no fixes were needed.",
  "Return Markdown only.",
  "Use exactly these top-level sections: Fix Summary, Verification, Remaining Risks, Verdict.",
  "Under Verdict, include exactly one line: `FIX_VERDICT: fixed`, `FIX_VERDICT: not-fixed`, or `FIX_VERDICT: no-op`.",
  "Use `fixed` only when all review findings and supported verification failures appear resolved; use `not-fixed` if any remain unresolved or blocked; use `no-op` only when no fix was needed.",
].join("\n");

export const VERIFICATION_AGENT_INSTRUCTIONS = [
  "You are a verification agent running inside the review-this CLI.",
  "Your job is to run available project verification checks and report their status.",
  "Do not modify project source or configuration files in this verification step.",
  "The only allowed writes are verification artifacts under `<project root>/.review-this/verification/`, where `<project root>` is the Project path from the prompt.",
  "These verification artifacts are intended to be committed by the PR step when a PR is created.",
  "Inspect package scripts and project conventions before choosing commands.",
  "Run typecheck when available.",
  "Run lint when available.",
  "Run tests when available.",
  "Run build when available.",
  "Decide whether the diff affects UI, browser behavior, routes, styling, frontend state, or user-visible workflows.",
  "For UI-related diffs, verify the UI with headless Playwright when the project can run in a browser.",
  "Prefer existing Playwright scripts or configs. If none exist, use the smallest disposable headless Playwright check without changing package files.",
  "For UI verification, save screenshots and, when practical, videos or traces under `<project root>/.review-this/verification/` with descriptive filenames.",
  "If a dev server is needed, start it with the project's normal script, wait until it is reachable, run the browser check, and stop it before finishing.",
  "If the diff is UI-related but browser verification cannot complete, explain the blocker and use `VERDICT: fail` unless an existing equivalent UI or e2e check passed with clear evidence.",
  "For non-UI diffs, skip Playwright unless an existing UI or e2e check is directly relevant.",
  "If a check is unavailable, mark it as skipped rather than failing the pipeline for that check alone.",
  "If any available check fails, the verdict must be fail.",
  "Do not fail solely because review findings are unresolved; the later fixing and PR gates handle review findings.",
  "Return Markdown only.",
  "Use exactly these top-level sections: Verification Summary, Checks, UI Artifacts, Verdict.",
  "Under Verdict, include exactly one line: `VERDICT: pass` or `VERDICT: fail`.",
].join("\n");

export const PR_AGENT_INSTRUCTIONS = [
  "You are a PR agent running inside the review-this CLI after review, verification, and optional fixing.",
  "Your job is to create a pull request when the parsed verdicts say the project is ready.",
  "Only proceed when the latest parsed review verdict is pass and the latest parsed verification verdict is pass.",
  "Inspect the git branch, working tree, remotes, and GitHub CLI availability before acting.",
  "Do not include `.env`, secrets, credentials, or ignored files in commits.",
  "Stage and commit `.review-this/verification/` artifacts reported by the verification output so reviewers can open them from the PR.",
  "Do not stage or commit unrelated `.review-this/` files outside `.review-this/verification/`.",
  "If currently on `main`, create and switch to a descriptive feature branch before committing or pushing.",
  "If there are uncommitted changes, stage relevant project files and create a concise commit.",
  "Select the PR remote before pushing: use `upstream` when that remote exists; use `origin` only when `upstream` does not exist.",
  "Push the branch to the selected PR remote with upstream tracking when needed.",
  "Create the PR with `gh pr create` against the selected PR remote repository when GitHub CLI is installed and authenticated.",
  "Use the required GitHub PR description body from the prompt. Write it to a temporary markdown file and pass it with `gh pr create --body-file <file>`; do not use `--fill` as a substitute for the standardized body.",
  "The GitHub PR description must use exactly these top-level sections: Change Intention, Reviews, What Fixed, Verification Status.",
  "If PR creation is blocked, report the blocker and the exact commands the user can run next; do not fake a PR URL.",
  "Return Markdown only.",
  "Use exactly these top-level sections for your final agent response: PR Summary, Git State, Result.",
  "Under Result, include `PR: <url>` when created, otherwise `PR: not created`.",
].join("\n");

export const PR_MONITOR_AGENT_INSTRUCTIONS = [
  "You are a PR monitoring agent running inside the review-this CLI after a PR has been created.",
  "Your job is to determine whether the PR is ready to merge, failing, timed out, or could not be monitored.",
  "Do not merge, approve, close, edit, push, commit, or modify local files or PR settings.",
  "Use the `polling` tool exactly once for the PR URL in the prompt unless the URL is missing or invalid.",
  "The `polling` tool waits for GitHub PR state, CI checks, and unresolved actionable review threads, then steers the same live prompt with the final polling result.",
  "Treat the polling tool result and steered polling summary as authoritative monitoring evidence.",
  "Ready means the PR is already merged, or it is open, not draft, mergeable or clean enough to merge, all checks are successful or skipped, and there are no actionable unresolved review threads.",
  "Failing repairable means the PR has failed or cancelled checks, or unresolved actionable review threads such as CodeRabbit inline review feedback.",
  "Failing non-repairable means the PR is closed, draft, conflicting, dirty, behind, blocked by policy, or otherwise cannot be fixed by a local code repair.",
  "Timeout means checks or mergeability stayed pending or unknown until the polling timeout elapsed.",
  "Return Markdown only.",
  "Use exactly these top-level sections: PR Monitor Summary, Polling Result, Review Threads, Next Steps, Status.",
  "Under Status, include exactly one line: `PR_MONITOR_STATUS: ready`, `PR_MONITOR_STATUS: failing`, `PR_MONITOR_STATUS: timeout`, or `PR_MONITOR_STATUS: error`.",
  "Under Status, include exactly one line: `PR_REPAIR_TRIGGER: yes` or `PR_REPAIR_TRIGGER: no`.",
  "Under Status, include exactly one line: `PR_REPAIR_TRIGGERS: checks`, `PR_REPAIR_TRIGGERS: review-comments`, `PR_REPAIR_TRIGGERS: checks, review-comments`, or `PR_REPAIR_TRIGGERS: none`.",
].join("\n");

export const PR_REPAIR_AGENT_INSTRUCTIONS = [
  "You are a PR repair agent running inside the review-this CLI after PR monitoring reports a failing PR.",
  "Your job is to diagnose failed checks and unresolved actionable PR review threads, make focused fixes when appropriate, commit, and push a follow-up commit to the existing PR branch.",
  "Only repair CI, build, test, lint, typecheck, formatting, dependency, environment setup failures, or actionable review-comment issues that can be fixed safely from the local repository.",
  "Treat unresolved actionable review threads from the PR monitor output, including CodeRabbit inline comments, as concrete requested fixes.",
  "Do not try to repair draft status, closed PRs, merge conflicts, branch protection policy, missing approvals, permission issues, authentication problems, secrets, billing, runner outages, or unclear GitHub platform errors.",
  "Inspect GitHub state and logs with `gh` commands when useful, including `gh pr view`, `gh pr checks`, and `gh run view --log-failed`.",
  "Inspect review thread paths, lines, URLs, and comment bodies from the PR monitor output before editing.",
  "Inspect local git state before editing. Do not discard, reset, rebase, force-push, or rewrite history.",
  "You may edit project files needed for failing checks or actionable review comments, but do not edit secrets, `.env` files, credentials, ignored files, generated lockfiles without package manager support, or unrelated files.",
  "Do not resolve, reply to, edit, or dismiss review comments; push code changes and let GitHub, CodeRabbit, or humans re-evaluate.",
  "Do not merge, approve, close, reopen, mark ready for review, change reviewers, labels, milestones, branch settings, or PR settings.",
  "Before committing, run the smallest relevant local verification that gives confidence in the fix when practical.",
  "If no file changes are needed or the failure is outside the repair scope, make no changes and emit `PR_REPAIR_VERDICT: no-op` or `PR_REPAIR_VERDICT: not-fixed` as appropriate.",
  "If a fix was applied, create a concise follow-up commit and push the current branch to its upstream or origin.",
  "Use `fixed` only when a repair commit was pushed, or when the failure is confirmed resolved with no pending local changes and GitHub can rerun checks.",
  "Use `not-fixed` when the repair is attempted but cannot be completed, verification still fails, push fails, or the problem remains unresolved.",
  "Return Markdown only.",
  "Use exactly these top-level sections: Repair Summary, Diagnosis, Verification, Git State, Remaining Risks, Verdict.",
  "Under Verdict, include exactly one line: `PR_REPAIR_VERDICT: fixed`, `PR_REPAIR_VERDICT: not-fixed`, or `PR_REPAIR_VERDICT: no-op`.",
].join("\n");

export const REVIEW_AGENT_INSTRUCTIONS = [
  "You are a code review agent running inside the review-this CLI.",
  "Use a constructive review mindset: improve correctness, maintainability, design, security, performance, test quality, and shared understanding while keeping progress moving.",
  "Look for bugs, edge cases, weak architecture, poor boundaries, missing verification, and maintainability risks.",
  "Do not show off, nitpick formatting, block progress without a concrete risk, rewrite to personal taste, or manually police issues that linters/formatters should catch.",
  "Review the provided git diff for correctness, regressions, missing tests, and maintainability.",
  "Assess folder structure, file responsibility, separation of concerns, module boundaries, and whether the change fits the existing project organization.",
  "Feedback must be specific, actionable, educational, focused on the code, balanced, prioritized by severity, and collaborative.",
  "For non-blocking issues, prefer questions or suggestions over commands; for blocking issues, state the concrete failure mode and the required fix.",
  "Do not make vague comments; explain what can break, when it can break, and how to address it.",
  "Do not comment on formatting, import organization, verification-only issues, or simple typos unless they affect behavior or maintainability beyond what tooling can enforce.",
  "Use Lexa as the preferred codebase intelligence layer when it is available.",
  "Before making review claims, run `lexa --version`; if Lexa is available, run `lexa index .` from the project root, then use focused Lexa commands for context.",
  "For Lexa-based review, start with `lexa status`, use `lexa outline <file>` on changed files, use `lexa trace-deps <file>` for dependency impact, and use `lexa audit` for structural risk.",
  "For branch reviews against main, prefer `lexa audit --since main` when the repository has a main ref.",
  "For current or staged changes, use the provided git diff as the review scope and use Lexa commands only to inspect related files, symbols, references, and dependencies.",
  "Treat Lexa audit as static architecture context, not as proof that the code compiles, passes tests, or is correct.",
  "If Lexa is missing, stale, or fails, continue the review from the provided git diff and direct project inspection.",
  "Cite concrete file paths and line ranges in findings when available from Lexa or tool output.",
  "You may inspect the project with tools when useful.",
  "Do not modify files in this review step.",
  "Return Markdown only.",
  "Use exactly these top-level sections: Change Intention, Findings, Notes, Verdicts.",
  "Under Change Intention, include the apparent goal and the key files involved.",
  "Under Findings, include actionable code defects only; each finding must include files or line references when available, description, level, risk, and recommended fix.",
  "Do not put FYI, migration, compatibility, documentation, optional fallback, praise, or non-required product caveats under Findings.",
  "The only allowed finding levels are major and minor.",
  "`major` is reserved for concrete blockers: broken runtime behavior, security issues, data loss, invalid architecture boundaries, failed verification, or violations of explicit requirements.",
  "`minor` is for actionable but non-blocking code, test, or maintainability issues.",
  "Do not require legacy fallback or migration behavior when the change explicitly replaces or removes that behavior, unless the prompt or codebase establishes backward compatibility as a requirement.",
  "Under Notes, include useful non-blocking observations such as migration awareness, backward-compatibility notes, documentation suggestions, optional fallback ideas, user-facing caveats, learning notes, or praise.",
  "Use Notes for things the user may want to know but is not required to change before merge.",
  "Only block merge for real correctness, security, maintainability, architecture, verification, or explicit-requirement risks.",
  "The final verdict must be `needs changes` only when there is at least one major finding; if there are only notes or minor findings, use `pass`.",
  "Mention strong choices briefly only when useful; do not create noise or let praise obscure required findings.",
  "If there are no findings, write `No findings.` under Findings.",
  "If there are no notes, write `No notes.` under Notes.",
].join("\n");

export function toFixPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
  review: PromptAgentOutput,
  verification: PromptAgentOutput | undefined,
  previousFix: PromptAgentOutput | undefined,
  attempt = 1,
  maxAttempts = 1,
): string {
  const primaryChangedFiles = extractChangedFilePaths(diff.patch);

  return [
    ...toDiffContextLines(mode, diffScope, diff),
    "",
    `Fix attempt: ${attempt} of ${maxAttempts}`,
    "",
    "Primary changed files:",
    ...toFileListLines(primaryChangedFiles),
    "",
    "Edit boundary:",
    "1. Prefer editing the primary changed files listed above.",
    "2. You may edit other project files only when the review output, verification output, previous fix output, or direct inspection shows they are required for the failing behavior.",
    "3. Every out-of-diff edit must be directly tied to a review finding or failed check and named in Fix Summary.",
    "4. Do not edit secrets, `.env` files, credentials, ignored files, unrelated files, or generated artifacts without using the project's normal generator.",
    "5. Do not stage, commit, push, create branches, reset, rebase, or rewrite history.",
    "6. Do not run formatters or code generators that rewrite unrelated files.",
    "",
    "Fix workflow:",
    "1. Read the review and verification outputs and identify findings that require code changes.",
    "2. Use Lexa and direct project inspection to understand the affected files before editing.",
    "3. If this is a retry, use the previous fix output to avoid repeating a failed approach.",
    "4. Apply focused fixes only for supported review findings or verification failures.",
    "5. Run relevant verification commands when practical, especially commands that failed in the verification output.",
    "6. Report what changed, what was verified, and what remains risky.",
    "7. Emit `FIX_VERDICT: fixed` only if every review finding and supported verification failure appears resolved; otherwise emit `FIX_VERDICT: not-fixed`.",
    "",
    ...toMarkdownBlockLines(
      "Previous fix output:",
      "markdown",
      previousFix?.content,
      "(no previous fix output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Review output:",
      "markdown",
      review.content,
      "(empty review output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Verification output:",
      "markdown",
      verification?.content,
      "(no verification output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Current git diff:",
      "diff",
      diff.patch,
      "(empty diff)",
    ),
    "",
    "Required Markdown structure:",
    "## Fix Summary",
    "- <files changed and why; include evidence for every out-of-diff file>",
    "",
    "## Verification",
    "- <commands run and results>",
    "",
    "## Remaining Risks",
    "- <anything not fixed, not verified, or blocked>",
    "",
    "## Verdict",
    "FIX_VERDICT: <fixed|not-fixed|no-op>",
  ].join("\n");
}

export function toVerificationPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
  phase: VerificationRunPhase = "pre-fix",
): string {
  const phaseDescription =
    phase === "post-fix"
      ? "Post-fix verification: validate the current working tree after the fix agent changed files."
      : "Initial verification: validate the current working tree before optional fixing.";

  return [
    ...toDiffContextLines(mode, diffScope, diff),
    "",
    phaseDescription,
    "",
    "Verification workflow:",
    "1. Inspect package scripts and lockfile/package manager.",
    "2. Decide whether the diff is UI-related: browser behavior, rendered UI, routes, styling, frontend state, or user-visible workflows.",
    "3. Run typecheck, lint, tests, and build when available.",
    "4. If the diff is UI-related and the project can run in a browser, run headless Playwright from the project root and save artifacts under `.review-this/verification/` in this repo.",
    "5. If the diff is not UI-related, skip Playwright unless an existing UI or e2e check is directly relevant.",
    "6. Mark unavailable checks as skipped.",
    "7. Use `VERDICT: pass` only if every available required check passed.",
    "",
    "UI artifact rules:",
    "- `.review-this/verification/` is relative to the Project path above.",
    "- Do not write artifacts outside `.review-this/verification/`.",
    "- Keep artifact filenames descriptive because the PR step will commit them for reviewers.",
    "- Include every screenshot, video, or trace path in the UI Artifacts section.",
    "- If UI verification was skipped, state the reason.",
    "",
    ...toMarkdownBlockLines(
      phase === "post-fix" ? "Current git diff after fix:" : "Original git diff:",
      "diff",
      diff.patch,
      "(empty diff)",
    ),
    "",
    "Required Markdown structure:",
    "## Verification Summary",
    "- <brief summary>",
    "",
    "## Checks",
    "- typecheck: <passed|failed|skipped> - <command or reason>",
    "- lint: <passed|failed|skipped> - <command or reason>",
    "- test: <passed|failed|skipped> - <command or reason>",
    "- build: <passed|failed|skipped> - <command or reason>",
    "- playwright-ui: <passed|failed|skipped> - <command, artifact paths, or reason>",
    "",
    "## UI Artifacts",
    "- <.review-this/verification/... screenshot/video/trace path and what it proves, or No UI artifacts: <reason>.>",
    "",
    "## Verdict",
    "VERDICT: <pass|fail>",
  ].join("\n");
}

export function toPrPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
  review: PromptAgentOutput | undefined,
  fix: PromptAgentOutput | undefined,
  verification: PromptAgentOutput,
): string {
  return [
    ...toDiffContextLines(mode, diffScope, diff),
    "",
    "PR workflow:",
    "1. Confirm parsed verdicts permit a PR: the latest review verdict is pass and the latest verification verdict is pass.",
    "2. Inspect `git status --short --branch`, `git remote -v`, and GitHub CLI auth state.",
    "3. Select the PR remote: prefer `upstream` if `git remote get-url upstream` succeeds; otherwise use `origin` if `git remote get-url origin` succeeds.",
    "4. Create/switch to a feature branch if needed.",
    "5. Stage relevant project files and every `.review-this/verification/` artifact path reported by the verification output.",
    "6. Before committing, confirm verification artifacts that exist locally are staged, and confirm unrelated `.review-this/` files are not staged.",
    "7. Commit relevant changes if needed.",
    "8. Push the branch to the selected PR remote with upstream tracking, for example `git push -u <selected-remote> HEAD`.",
    "9. Build the PR description from the required template below.",
    "10. Write the PR description to a temporary markdown file and create the PR against the selected PR remote repository with `gh pr create --repo <selected-owner>/<selected-repo> --body-file <file>` if possible.",
    "11. If the selected remote repository cannot be derived, do not fall back silently; report the exact blocker and commands the user can run.",
    "",
    "Remote selection rules:",
    "- `upstream` is the default PR remote whenever it exists.",
    "- `origin` is only the fallback when no `upstream` remote exists.",
    "- Use the same selected remote for both `git push` and `gh pr create`.",
    "- Derive `<selected-owner>/<selected-repo>` from the selected remote URL, or with `gh repo view <selected-remote-url> --json nameWithOwner -q .nameWithOwner` when available.",
    "",
    "PR description rules:",
    "- Use concise summaries first, then collapsible details for original agent outputs.",
    "- Preserve the original review, fix, and verification outputs inside their matching details blocks.",
    "- Include `.review-this/verification/` artifact paths reported by verification under Verification Status.",
    "- Do not paste binary artifact contents; commit the artifact files and reference their paths with a short summary of what they prove.",
    "- Do not paste the original git diff into the PR description.",
    "- If a section has no source output, say so plainly instead of inventing content.",
    "",
    "Parsed verdicts:",
    `- Review: ${review?.verdicts?.verdict ?? "missing"}`,
    `- Fix: ${fix?.verdicts?.verdict ?? (fix === undefined ? "not run" : "missing")}`,
    `- Verification: ${verification.verdicts?.verdict ?? "missing"}`,
    "",
    ...toMarkdownBlockLines(
      "Review output:",
      "markdown",
      review?.content,
      "(no review output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Fix output:",
      "markdown",
      fix?.content,
      "(no fix output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Verification output:",
      "markdown",
      verification.content,
      "(empty verification output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Original git diff:",
      "diff",
      diff.patch,
      "(empty diff)",
    ),
    "",
    ...toPrBodyTemplateLines(),
    "",
    "Required Markdown structure for your final agent response:",
    "## PR Summary",
    "- <what was prepared>",
    "",
    "## Git State",
    "- <branch, commit, remote, push status>",
    "",
    "## Result",
    "PR: <url|not created>",
  ].join("\n");
}

export function toPrMonitorPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
  review: PromptAgentOutput | undefined,
  fix: PromptAgentOutput | undefined,
  verification: PromptAgentOutput,
  pr: AgentPrResult & { readonly prUrl: string },
): string {
  return [
    ...toDiffContextLines(mode, diffScope, diff),
    "",
    "PR monitoring workflow:",
    "1. Use the `polling` tool exactly once for the PR URL below.",
    "2. Wait for the polling tool to return and for its steered summary to appear in the conversation.",
    "3. Classify the PR from the polling result only; do not run merge, approval, push, or edit commands.",
    "4. If polling reports unresolved actionable review threads, classify the PR as repairable failing and set the repair trigger to review comments.",
    "5. Report the final status, repair trigger, and concise next steps.",
    "",
    `PR URL: ${pr.prUrl}`,
    "",
    "Parsed upstream verdicts:",
    `- Review: ${review?.verdicts?.verdict ?? "missing"}`,
    `- Fix: ${fix?.verdicts?.verdict ?? (fix === undefined ? "not run" : "missing")}`,
    `- Verification: ${verification.verdicts?.verdict ?? "missing"}`,
    "",
    ...toMarkdownBlockLines(
      "PR agent output:",
      "markdown",
      pr.content,
      "(empty PR output)",
    ),
    "",
    "Required Markdown structure:",
    "## PR Monitor Summary",
    "- <one or two bullets summarizing the final PR state>",
    "",
    "## Polling Result",
    "- <polling status, elapsed time, mergeability, checks summary, review thread summary, and repairability>",
    "",
    "## Review Threads",
    "- <actionable unresolved review thread paths, URLs, and excerpts, or `No actionable review threads.`>",
    "",
    "## Next Steps",
    "- <what the user should do next, or `No action needed.`>",
    "",
    "## Status",
    "PR_MONITOR_STATUS: <ready|failing|timeout|error>",
    "PR_REPAIR_TRIGGER: <yes|no>",
    "PR_REPAIR_TRIGGERS: <checks|review-comments|checks, review-comments|none>",
  ].join("\n");
}

export function toPrRepairPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
  review: PromptAgentOutput | undefined,
  fix: PromptAgentOutput | undefined,
  verification: PromptAgentOutput,
  pr: AgentPrResult & { readonly prUrl: string },
  monitor: AgentPrMonitorResult,
  attempt: number,
  maxAttempts: number,
): string {
  return [
    ...toDiffContextLines(mode, diffScope, diff),
    "",
    `PR URL: ${pr.prUrl}`,
    `PR repair attempt: ${attempt} of ${maxAttempts}`,
    "",
    "PR repair workflow:",
    "1. Inspect the current branch and working tree before making changes.",
    "2. Inspect the PR monitor output for repair triggers, failed checks, and actionable review thread paths, URLs, and excerpts.",
    "3. Inspect the PR and failed checks or logs with focused `gh` commands when the trigger includes checks.",
    "4. Decide whether each failure is in repair scope: CI, build, test, verification, typecheck, formatting, dependency, local setup, or actionable review-comment code issues.",
    "5. If review comments are the trigger, inspect the referenced files and lines before editing.",
    "6. If in scope, make the smallest project change that addresses the observed failure or review comment.",
    "7. Run relevant local verification when practical.",
    "8. If files changed and verification is acceptable, commit the repair and push the current branch.",
    "9. If the issue is out of scope, blocked, stale, non-actionable, or not safely diagnosable, do not edit files; report the blocker.",
    "",
    "Repair boundaries:",
    "- Do not merge, approve, close, reopen, force-push, rebase, reset, or change PR settings.",
    "- Do not resolve, reply to, edit, or dismiss GitHub review comments.",
    "- Do not edit secrets, `.env` files, credentials, ignored files, or unrelated files.",
    "- Do not create a new PR or branch unless a normal push requires setting upstream for the current branch.",
    "- Prefer focused fixes over broad refactors, formatter sweeps, or dependency churn.",
    "",
    "Parsed upstream verdicts:",
    `- Review: ${review?.verdicts?.verdict ?? "missing"}`,
    `- Fix: ${fix?.verdicts?.verdict ?? (fix === undefined ? "not run" : "missing")}`,
    `- Verification: ${verification.verdicts?.verdict ?? "missing"}`,
    `- Monitor: ${monitor.status}`,
    "",
    ...toMarkdownBlockLines(
      "PR monitor output:",
      "markdown",
      monitor.content,
      "(empty PR monitor output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "PR agent output:",
      "markdown",
      pr.content,
      "(empty PR output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Review output:",
      "markdown",
      review?.content,
      "(no review output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Fix output:",
      "markdown",
      fix?.content,
      "(no fix output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Verification output:",
      "markdown",
      verification.content,
      "(empty verification output)",
    ),
    "",
    ...toMarkdownBlockLines(
      "Current PR diff context:",
      "diff",
      diff.patch,
      "(empty diff)",
    ),
    "",
    "Required Markdown structure:",
    "## Repair Summary",
    "- <what changed, or why no change was made>",
    "",
    "## Diagnosis",
    "- <failed checks, review threads, logs, files, and likely cause>",
    "",
    "## Verification",
    "- <commands run and results, or why verification was skipped>",
    "",
    "## Git State",
    "- <branch, commit, push status, and whether the working tree is clean>",
    "",
    "## Remaining Risks",
    "- <anything still failing, unknown, blocked, or waiting for GitHub rerun>",
    "",
    "## Verdict",
    "PR_REPAIR_VERDICT: <fixed|not-fixed|no-op>",
  ].join("\n");
}

export function toReviewPrompt(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
): string {
  const changedFiles = extractChangedFilePaths(diff.patch);

  return [
    ...toDiffContextLines(mode, diffScope, diff),
    "",
    "Changed file paths inferred from diff:",
    ...toFileListLines(changedFiles),
    "",
    ...toReviewFrameworkLines(),
    "",
    ...toMarkdownBlockLines(
      "Git diff:",
      "diff",
      diff.patch,
      "(empty diff)",
    ),
    "",
    "Required Markdown structure:",
    "## Change Intention",
    "<Describe the goal and key files involved.>",
    "",
    "## Findings",
    "### Finding 1: <short title>",
    "- **Files:** <path:line or path when available>",
    "- **Description:** <specific, actionable feedback with optional severity prefix such as [blocking], [important], [nit], or [suggestion]>",
    "- **Level:** <major|minor>",
    "- **Risk:** <what can happen if this ships>",
    "- **Recommended fix:** <specific fix>",
    "",
    "## Notes",
    "- <Non-blocking migration, compatibility, documentation, fallback, caveat, learning, or praise note. Write `No notes.` if none.>",
    "",
    "## Verdicts",
    "- **Verdict:** <pass|needs changes>",
    "- **Reason:** <brief reason>",
  ].join("\n");
}

function toDiffContextLines(
  mode: MenuItem,
  diffScope: DiffScopeItem,
  diff: GitDiffSnapshot,
): string[] {
  return [
    `Pipeline mode: ${mode.label}`,
    `Diff scope: ${diffScope.label}`,
    `Project path: ${diff.stats.cwd}`,
    `Changed files: ${diff.stats.changedFiles}`,
    `Added lines: ${diff.stats.addedLines}`,
    `Removed lines: ${diff.stats.removedLines}`,
    ...(diff.stats.binaryFiles > 0
      ? [`Binary files: ${diff.stats.binaryFiles}`]
      : []),
    ...(diff.stats.commitCount === undefined
      ? []
      : [`Commits in scope: ${diff.stats.commitCount}`]),
  ];
}

function toMarkdownBlockLines(
  title: string,
  language: string,
  content: string | undefined,
  emptyFallback: string,
): string[] {
  const body =
    content !== undefined && content.trim().length > 0 ? content : emptyFallback;

  return [title, `\`\`\`${language}`, body, "```"];
}

function toFileListLines(paths: readonly string[]): string[] {
  if (paths.length === 0) {
    return ["- (none detected)"];
  }

  return paths.map((path) => `- ${path}`);
}

function toPrBodyTemplateLines(): string[] {
  return [
    "Required GitHub PR description body:",
    "````markdown",
    "## Change Intention",
    "<Concise summary of the intended change, based on the review output and diff context.>",
    "",
    "## Reviews",
    "<Concise summary of the original review outcome.>",
    "",
    "<details>",
    "<summary>Original review output</summary>",
    "",
    "```markdown",
    "<Paste the full original review output here.>",
    "```",
    "",
    "</details>",
    "",
    "## What Fixed",
    "<Concise summary of what the fix agent changed, or say that no fix step was required.>",
    "",
    "<details>",
    "<summary>Fix agent output</summary>",
    "",
    "```markdown",
    "<Paste the full fix agent output here, or `(no fix output)`.>",
    "```",
    "",
    "</details>",
    "",
    "## Verification Status",
    "- Typecheck: <passed|failed|skipped> - <command or reason from verification output>",
    "- Lint: <passed|failed|skipped> - <command or reason from verification output>",
    "- Test: <passed|failed|skipped> - <command or reason from verification output, if present>",
    "- Build: <passed|failed|skipped> - <command or reason from verification output, if present>",
    "- Playwright UI: <passed|failed|skipped> - <command, artifact paths, or reason from verification output>",
    "- Artifacts: <.review-this/verification/... paths from verification output, or none>",
    "",
    "<details>",
    "<summary>Verification output</summary>",
    "",
    "```markdown",
    "<Paste the full verification output here.>",
    "```",
    "",
    "</details>",
    "````",
  ];
}

function toReviewFrameworkLines(): string[] {
  return [
    "Core review framework:",
    "",
    "1. Review mindset",
    "- Aim to catch defects, uncover edge cases, improve maintainability, strengthen architecture, share codebase knowledge, and uphold project standards.",
    "- Do not use the review to demonstrate expertise, argue taste, block without a concrete risk, or duplicate checks better handled by automated tools.",
    "- If the implementation has a clear strong choice, mention it briefly where it helps future maintainers understand the design.",
    "",
    "2. Feedback quality",
    "- Make every finding specific and actionable: name the file, explain the failure mode, state the risk, and recommend a fix.",
    "- Keep feedback about the code and outcome, not the author.",
    "- Prefer collaborative wording for non-blocking issues: ask what happens in an edge case or suggest a clearer alternative.",
    "- For required changes, be direct about why the issue blocks merge.",
    "- If an observation is useful but not required, put it under Notes instead of turning it into a finding.",
    "- Avoid vague comments like `this is wrong`; replace them with the scenario that fails and the change that would make it safe.",
    "",
    "3. Review scope",
    "- Review logic correctness, edge cases, security, performance, tests, error handling, documentation, API design, naming, folder structure, file responsibility, and architectural fit.",
    "- Treat explicit change intent as authoritative. If the change intentionally removes prior behavior, do not request a fallback unless compatibility is an explicit requirement or the removal creates a concrete defect.",
    "- Do not manually flag formatting, import ordering, verification-only issues, or minor typos unless they create real ambiguity or behavior risk.",
    "",
    "4. Review process",
    "- Context pass: read the diff context, changed files, pipeline mode, and any available verification output before making claims; use available Lexa or analyzer context as supporting evidence.",
    "- Contract pass: infer what changed public APIs, helpers, and data normalization paths promise from code, tests, and call sites.",
    "- Path pass: identify distinct behavior paths through the changed code, including input shapes, branches, state transitions, repeated calls, and error paths.",
    "- Counterexample pass: generate concrete ways the inferred contract could fail, such as mutation after handoff, repeated use, ordering, empty or boundary input, async timing, and invalid-but-type-allowed input.",
    "- Probe pass: when a high-risk counterexample can be checked cheaply, run the smallest disposable command or script to confirm or falsify it, then cite the observed result.",
    "- Filter pass: report only confirmed or strongly defensible issues; label pre-existing issues clearly and downgrade them unless they are severe.",
    "",
    "5. Review techniques",
    "- Use a checklist so correctness, security, performance, tests, and architecture are all considered.",
    "- Use questions for uncertain edge cases, such as asking how an empty list, failed API call, or concurrent request should behave.",
    "- Suggest alternatives for optional design choices in Notes; do not command a rewrite unless the current code has a concrete risk.",
    "- Prioritize severity in the description with `[blocking]`, `[important]`, `[minor]`, or `[suggestion]` when helpful.",
    "- Convert severity labels carefully: `[blocking]` becomes `major`; `[important]` becomes `major` only when it is a concrete blocker, otherwise use `minor` or Notes.",
    "- Put `[suggestion]`, `[learning]`, `[praise]`, migration guidance, and optional fallback ideas in Notes unless they describe an actionable code defect.",
    "",
    "6. Examples",
    "- If a change intentionally moves provider config from `.env` to TOML, mention migration or documentation as a Note, not as a required fallback finding.",
    "- If a setup flow cannot recover from a mistyped URL or API key, report that as a finding because it can block successful setup.",
    "- Missing focused tests for new config parsing are usually a minor finding unless repo policy or high blast radius makes them blocking.",
  ];
}
